[BUGFIX] Fix warnings in DataHandlerHook
hoogi91/spreadsheets pull request #644
Opened 2024-10-24 08:28 UTC by dkd-friedrich

Fixes 2 PHP warnings that might occur in DataHandlerHook:
- Undefined array key "columnsOverrides"
- Undefined array key "tx_spreadsheets_assets"

| Q             | A
| ------------- | ---
| Bug fix?      | yes 
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #603

2025-04-10 17:37 UTC, wrock requested changes
line 84 needs to be:
if (($fieldArray[$uploadField] ?? 1) === 0) {
otherwise already attached spreadsheets will be unlinked, when key $uploadField does not exist!

2025-04-10 17:37 UTC, wrock commented on Classes/Hooks/DataHandlerHook.php
> +            if (($fieldArray[$uploadField] ?? 0) === 0) {
this line needs to be:
 if (($fieldArray[$uploadField] ?? 1) === 0) {
otherwise already attached spreadsheets will be unlinked, when  key $uploadField does not exist!

2025-06-12 12:11 UTC, wrock approved these changes

2025-10-20 18:16 UTC, closed without merging

2025-10-20 18:16 UTC, hoogi91 commented
should be now solved with https://github.com/hoogi91/spreadsheets/releases/tag/4.0.3